import { escapeHtml } from './util.mjs';

const escapeMarkdown = value => String(value ?? '').replace(/\\/g, '\\\\').replace(/[<>]/g, c => c === '<' ? '&lt;' : '&gt;').replace(/([\[\]])/g, '\\$1');

export function renderMarkdown(report) {
  const out = [`# DesignSignal 337/902 - ${report.date}`, '', `Evidence baseline: \`${report.evidence.version}\` / \`${report.evidence.hash}\``, ''];
  for (const item of report.items) out.push(`## ${escapeMarkdown(item.title.zh)} / ${escapeMarkdown(item.title.en)}`, '', escapeMarkdown(item.synopsis.zh), '', escapeMarkdown(item.synopsis.en), '', `- Source: [${escapeMarkdown(item.source.name)}](${item.source.url})`, `- 337: ${item.exam['337'].map(escapeMarkdown).join(', ')}`, `- 902: ${item.exam['902'].map(escapeMarkdown).join(', ')}`, `- Confidence: ${item.confidence}`, '', `**局限 / Limits:** ${escapeMarkdown(item.analysis.zh.limits)} / ${escapeMarkdown(item.analysis.en.limits)}`, '');
  out.push('## Exercise', '', `Timebox: ${report.exercise.timeboxMinutes} minutes`, '', report.exercise.prompt, '', ...report.exercise.deliverables.map(x => `- ${x}`), '', '## Hypotheses', '', ...report.synthesis.hypotheses.map(x => `- ${x.claim} (${x.confidence}); counterevidence: ${x.counterevidence.join(' ')}`));
  return `${out.join('\n')}\n`;
}

const itemHtml = item => `<article class="signal" data-category="${escapeHtml(item.category)}">
  ${item.image ? `<img src="${escapeHtml(item.image.localCacheRef || item.image.url)}" alt="" loading="lazy" referrerpolicy="no-referrer">` : ''}
  <div><p class="meta">${escapeHtml(item.category.toUpperCase())} · ${escapeHtml(item.source.name)} · ${(item.confidence * 100).toFixed(0)}%</p><h2>${escapeHtml(item.title.zh)}</h2><p class="en">${escapeHtml(item.title.en)}</p><p>${escapeHtml(item.synopsis.zh)}</p><p class="en">${escapeHtml(item.synopsis.en)}</p>
  <details><summary>证据与方法 / Evidence & method</summary><p>${escapeHtml(item.analysis.zh.evidence)}</p><p>${escapeHtml(item.analysis.en.method)}</p><p><strong>Limits:</strong> ${escapeHtml(item.analysis.en.limits)}</p><a href="${escapeHtml(item.source.url)}" rel="noopener noreferrer">Primary source</a></details>
  <p class="tags">337 · ${item.exam['337'].map(escapeHtml).join(' · ')}</p><p class="tags">902 · ${item.exam['902'].map(escapeHtml).join(' · ')}</p></div></article>`;

export function renderHtml(report) {
  const health = report.audit.sourceHealth.map(x => `<li><span class="dot ${x.status}"></span>${escapeHtml(x.sourceId)} <small>${escapeHtml(x.status)} · ${x.count}</small></li>`).join('');
  const hypotheses = report.synthesis.hypotheses.map(x => `<li><meter min="0" max="1" value="${x.confidence}"></meter><strong>${escapeHtml(x.claim)}</strong><span>Counterevidence: ${escapeHtml(x.counterevidence.join(' '))}</span></li>`).join('');
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title>DesignSignal ${escapeHtml(report.date)}</title><style>
  :root{--ink:#18201d;--muted:#5c6963;--line:#d9dfdc;--paper:#f7f8f6;--white:#fff;--green:#176b50;--red:#a04437;--blue:#245b91}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:15px/1.55 system-ui,-apple-system,"Segoe UI",sans-serif;letter-spacing:0}header{border-bottom:1px solid var(--line);background:var(--white);position:sticky;top:0;z-index:2}.bar,main{max-width:1180px;margin:auto;padding:14px 24px}.bar{display:flex;align-items:center;gap:20px}.brand{font-weight:750;font-size:18px}.date{color:var(--muted)}nav{margin-left:auto;display:flex;gap:4px}button{border:1px solid var(--line);background:white;padding:7px 11px;border-radius:5px;color:var(--ink);cursor:pointer}button[aria-pressed="true"]{background:var(--ink);color:white}main{display:grid;grid-template-columns:minmax(0,1fr) 280px;gap:30px}.feed{min-width:0}.signal{display:grid;grid-template-columns:180px 1fr;gap:20px;padding:24px 0;border-bottom:1px solid var(--line)}.signal img{width:180px;aspect-ratio:4/3;object-fit:cover;background:#e2e6e4}.meta,.en,.tags,small{color:var(--muted)}h1{font-size:22px;margin:20px 0 2px}h2{font-size:20px;margin:3px 0}.en{margin-top:0}.tags{font-size:13px}details{border-left:3px solid var(--blue);padding-left:12px}summary{cursor:pointer;font-weight:650}aside{border-left:1px solid var(--line);padding-left:24px}aside section{padding:18px 0;border-bottom:1px solid var(--line)}h3{font-size:15px;margin:0 0 10px}ul{padding-left:18px}.health{list-style:none;padding:0}.health li{display:flex;gap:7px;align-items:center}.health small{margin-left:auto}.dot{width:8px;height:8px;border-radius:50%;background:var(--red)}.dot.ok{background:var(--green)}.forecast li{margin-bottom:14px}.forecast span{display:block;color:var(--muted);font-size:12px}meter{width:100%;height:7px;display:block;margin-bottom:4px}.exercise{background:#edf2ef;border-left:3px solid var(--green);padding:12px}.hidden{display:none!important}@media(max-width:800px){main{grid-template-columns:1fr}.bar{flex-wrap:wrap}nav{width:100%;margin:0;overflow:auto}aside{border-left:0;padding-left:0}.signal{grid-template-columns:1fr}.signal img{width:100%;max-height:280px}}
  </style></head><body><header><div class="bar"><div class="brand">DesignSignal 337/902</div><div class="date">${escapeHtml(report.date)}</div><nav aria-label="Filters"><button data-filter="all" aria-pressed="true">All</button><button data-filter="paper">Papers</button><button data-filter="product">Product</button><button data-filter="ui">UI</button><button data-filter="frontier">Frontier</button></nav></div></header><main><section class="feed"><h1>今日研究信号 / Daily research signals</h1><p class="en">Evidence baseline ${escapeHtml(report.evidence.version)} · ${escapeHtml(report.evidence.hash.slice(0,12))}</p>${report.items.map(itemHtml).join('')}</section><aside><section><h3>Source health</h3><ul class="health">${health}</ul></section><section><h3>Exam map</h3><p>337: research foundations 75 · engineering 75</p><p>902: critique 50 · system 50 · expression/plan 50</p></section><section><h3>Forecast confidence</h3><ul class="forecast">${hypotheses}</ul></section><section><h3>Core exercise · ${report.exercise.timeboxMinutes} min</h3><div class="exercise">${escapeHtml(report.exercise.prompt)}</div></section><section><h3>Next-day feedback</h3><form method="post" action="/api/feedback"><label>What failed or transferred?<textarea name="note" maxlength="2000" rows="4" style="width:100%"></textarea></label><button type="submit">Record</button></form></section></aside></main><script src="/app.js"></script></body></html>`;
}
